//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityImporter.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActivityImporter.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO users(upn)
        ///	SELECT distinct imports.user_name 
        ///	FROM ${STAGING_TABLE_ACTIVITY} imports
        ///	left join users on users.upn = imports.user_name
        ///	where users.upn is null;
        ///
        ///INSERT INTO event_file_ext([name])
        ///	SELECT distinct imports.extension_name 
        ///	FROM ${STAGING_TABLE_ACTIVITY} imports
        ///	left join event_file_ext on event_file_ext.[name] = imports.extension_name
        ///	where event_file_ext.[name] is null and imports.extension_name is not null and imports.extension_name != &apos;&apos;;
        ///
        ///INSERT INTO event_fil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string insert_activity_from_staging_table {
            get {
                return ResourceManager.GetString("insert_activity_from_staging_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO urls(full_url)
        ///	SELECT distinct imports.url 
        ///	FROM [${STAGING_TABLE_ACTIVITY}] imports
        ///	left join 
        ///		urls on urls.full_url = imports.url
        ///	where 
        ///		not exists(select top 1 full_url from urls where full_url = imports.url)
        ///
        ///
        ///INSERT INTO sites(url_base)
        ///	SELECT distinct imports.url_base 
        ///	FROM [${STAGING_TABLE_ACTIVITY}] imports
        ///	left join 
        ///		sites on sites.url_base = imports.url_base
        ///	where 
        ///		imports.url_base is not null AND 
        ///		not exists(select top 1 url_base from sites where url_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string insert_sp_copilot_events_from_staging_table {
            get {
                return ResourceManager.GetString("insert_sp_copilot_events_from_staging_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO online_meetings(created, meeting_id, name)
        ///	SELECT distinct meeting_created_utc, imports.meeting_id, imports.meeting_name 
        ///	FROM ${STAGING_TABLE_ACTIVITY} imports
        ///	left join 
        ///		online_meetings on online_meetings.meeting_id = imports.meeting_id
        ///	where 
        ///		not exists(select top 1 created, meeting_id, name from online_meetings 
        ///			where created = imports.meeting_created_utc 
        ///				and created = imports.meeting_created_utc 
        ///				and imports.meeting_name = [name]
        ///		)
        ///
        ///insert into [event_copil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string insert_teams_copilot_events_from_staging_table {
            get {
                return ResourceManager.GetString("insert_teams_copilot_events_from_staging_table", resourceCulture);
            }
        }
    }
}
