#See https://aka.ms/overrideVSDockerComposeConfiguration to understand how Visual Studio uses this override file.
services:
  web.server:
    build:
      dockerfile: Web\Web.Server\Dockerfile.release

    environment:
      - VITE_MSAL_CLIENT_ID=5023a8dc-8448-4f41-b34c-131ee03def2f
      - VITE_MSAL_AUTHORITY=https://login.microsoftonline.com/organizations
      - VITE_MSAL_SCOPES=api://localhost:5173/5023a8dc-8448-4f41-b34c-131ee03def2f/access
      - VITE_TEAMSFX_START_LOGIN_PAGE_URL=https://localhost:5173/auth-start.html
      - VITE_API_ENDPOINT=https://localhost:5173
