services:

  copilotbot-web:
    image: copilotbot-web
    build:
      context: .
      dockerfile: Web/Web.Server/Dockerfile
    ports:
    - "80:8080"
  copilotbot-functions:
    image: copilotbot-functions
    build:
        context: .
        dockerfile: Functions/Dockerfile
