services:
  web.server:
    build:
      context: .
      dockerfile: Web\Web.Server\Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      ACCEPT_EULA: "Y" 
      MSSQL_SA_PASSWORD: "DevStrong@Passw0rd"
    ports: 
      - "1433:1433" 
    container_name: sql
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"